version: '3.8'

services:
  backend:
    build: .
    container_name: loyalty-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres: # <--- MODIFY THIS SECTION
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: loyalty-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # <--- ADD THIS ENTIRE SECTION
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: